project_name: "redirect"
builds:
  - binary: redirect
    main: cmd/redirect/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
dockers:
  - image_templates:
      - "ghcr.io/pedrokiefer/{{ .ProjectName }}:{{ .Version }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
    extra_files:
      - ui
  - image_templates:
      - "ghcr.io/pedrokiefer/{{ .ProjectName }}:{{ .Version }}-arm64v8"
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
    extra_files:
      - ui

docker_manifests:
  - name_template: ghcr.io/pedrokiefer/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/pedrokiefer/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/pedrokiefer/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: ghcr.io/pedrokiefer/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/pedrokiefer/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/pedrokiefer/{{ .ProjectName }}:{{ .Version }}-arm64v8

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
